##### Build and Test stage
FROM maven:3.5.2-jdk-8-alpine AS build
WORKDIR /usr/src/app
ENV MVN_SETTINGS=/usr/share/maven/ref/settings-docker.xml

# 1. Only update dependencies when the pom.xml actually changed.
COPY ./k4r-adapter-rest/pom.xml .
RUN mvn -s $MVN_SETTINGS dependency:go-offline

# 2. Do the actual build.
COPY ./k4r-adapter-rest/src src
RUN mvn -s $MVN_SETTINGS package

##### Production stage
FROM openjdk:8-jre-alpine
RUN addgroup -S hdda_app && adduser -S hdda_app -G hdda_app
USER hdda_app:hdda_app
WORKDIR /usr/app
COPY --from=build /usr/src/app/target/adapter.jar hetida-designer-adapter-k4r-java.jar
EXPOSE 8093
ENTRYPOINT ["java", "-jar", "hetida-designer-adapter-k4r-java.jar"]
